### ISSUE TITLE
HTTP Response codes

### ISSUE THREAD

**Issue by CMCDragonkai** [noetix/pin-php#11]
Pin sends back HTTP response codes, some of these indicate errors. Is it possible to retrieve these response codes using your library?

**Comment by noetix** [comment]
Buzz will always return an object regardless of the outcome. Therefore `$service->submit($request)` will always return something, without exception or warnings.

I thought about adding some validation to ensure its a JSON response but frankly the response side of things is up to the end user. The library just helps with request building and transport.
